CREATE TABLE Bull (
	id INTEGER PRIMARY KEY,
	active INTEGER,
	name TEXT,
	regNum TEXT,
	dateOfBirth DATE,
	birthWeight REAL,
	breed TEXT,
	color TEXT,
	specialMarkings TEXT,
	importExport TEXT,
	earTag TEXT,
	earTagLoc TEXT,
	brandNum TEXT,
	brandNumLoc TEXT,
	tattoo TEXT,
	tattooLoc TEXT,
	electronicId TEXT,
	electronicIdLoc TEXT,
	otherId TEXT,
	otherIdLoc TEXT,
	metalId TEXT,
	metalIdLoc TEXT,
	genetic TEXT,
	bloodline TEXT,
	siblingCode TEXT,
	cloned TEXT,
	showAnimal INTEGER,
	aiBull INTEGER,
	reference INTEGER,
	hornStatus TEXT,
	origin TEXT,
	imagePath TEXT,
	pasture TEXT,
	pen TEXT,
	currBullOwner TEXT,
	bullSire TEXT,
	bullDame TEXT,
	comments TEXT,
	purchaseFrom TEXT,
	purchaseDate TEXT,
	price REAL,
	breeder TEXT
);

CREATE TABLE Cow (
	id INTEGER PRIMARY KEY,
	active INTEGER,
	name TEXT,
	regNum TEXT,
	dateOfBirth DATE,
	birthWeight REAL,
	breed TEXT,
	color TEXT,
	specialMarkings TEXT,
	importExport TEXT,
	earTag TEXT,
	earTagLoc TEXT,
	brandNum TEXT,
	brandNumLoc TEXT,
	tattoo TEXT,
	tattooLoc TEXT,
	electronicId TEXT,
	electronicIdLoc TEXT,
	otherId TEXT,
	otherIdLoc TEXT,
	metalId TEXT,
	metalIdLoc TEXT,
	genetic TEXT,
	bloodline TEXT,
	siblingCode TEXT,
	cloned TEXT,
	showAnimal INTEGER,
	aiCow INTEGER,
	reference INTEGER,
	hornStatus TEXT,
	origin TEXT,
	imagePath TEXT,
	pasture TEXT,
	pen TEXT,
	currCowOwner TEXT,
	cowSire TEXT,
	cowDame TEXT,
	comments TEXT,
	purchaseFrom TEXT,
	purchaseDate TEXT,
	price REAL,
	breeder TEXT
);

CREATE TABLE BullMortality (
	bullId INTEGER,
	dateOfDeath DATE,
	causeOfDeath TEXT,
	location TEXT,
	symptoms TEXT,
	policy TEXT,
	insured TEXT,
	insurance TEXT,
	policyNum TEXT,
	phone TEXT,
	coverageDate DATE,
	coverageAmount REAL,
	ratePercentage REAL,
	premium REAL,
	term REAL,
	autopsy TEXT,
	results TEXT,
	resultsUploaded TEXT,
	veterinarian TEXT,
	vetFee REAL,
	date DATE,
	mortalityComments TEXT,
	carcassType TEXT,
	killDate DATE,
	killComment TEXT,
	processingFacility TEXT,
	feederWeight REAL,
	liveWeight REAL,
	carcassWeight REAL,
	ribeyeArea TEXT,
	ribeyeAreaCWT TEXT,
	fatThickness TEXT,
	intramascularFat TEXT,
	marbling TEXT,
	frameScore TEXT,
	maturity TEXT,
	qualityGrade TEXT,
	yieldGrade TEXT,
	penLot TEXT,
	tenderness TEXT,
	carcassValue TEXT,
	dressingPercentage TEXT,
	reportNum TEXT,
	carcassNum TEXT,
	lotNum TEXT,
	daysOnFeed TEXT,
	carcassComments TEXT,
	CONSTRAINT BullMortality_PK UNIQUE (bullId),
	CONSTRAINT BullMortality_Bull_FK FOREIGN KEY (bullId) REFERENCES Bull(id)
		ON DELETE CASCADE ON UPDATE CASCADE
);

-- INDEXES
CREATE INDEX Bull_active_IDX ON Bull (active) ;
CREATE INDEX Bull_name_IDX ON Bull (name) ;

CREATE INDEX Cow_active_IDX ON Cow (active) ;
CREATE INDEX Cow_name_IDX ON Cow (name) ;
